FROM alpine:latest
MAINTAINER lei fireflykind@gmail.com
RUN echo "http://mirrors.ustc.edu.cn/alpine/v3.2/main/" > /etc/apk/repositories
RUN apk --update add bash
RUN apk add gcc
RUN apk add g++
RUN apk add python
RUN apk add python-dev
RUN apk add py-pip
RUN pip install jupyter
