FROM alpine:latest
MAINTAINER lei fireflykind@gmail.com

#mirr apk repositories
#RUN echo "http://mirrors.ustc.edu.cn/alpine/v3.2/main/" > /etc/apk/repositories

RUN echo "http://mirrors.ustc.edu.cn/alpine/v3.3/main/" > /etc/apk/repositories

RUN apk --update add bash
RUN apk add gcc
RUN apk add g++
RUN apk add python python-dev py-pip gfortran build-base
#RUN apk add freetype libpng
#RUN apk add freetype-dev libpng-dev

RUN mkdir ~/.pip/
RUN echo "[global]" > ~/.pip/pip.conf

#mirr pip 
RUN echo "index-url = https://pypi.mirrors.ustc.edu.cn/simple" >> ~/.pip/pip.conf

RUN pip install --upgrade pip

RUN pip install -v numpy==1.9.0
RUN pip install -v pandas==0.14.1

RUN pip install requests
#RUN pip install Matplotlib
#RUN pip install seaborn

RUN pip install jupyter

RUN rm -rf /var/cache/apk/* /tmp/* /root/src/

EXPOSE 8888
VOLUME ["/data/notebooks"]
COPY jupyterNoteBooks.sh /jupyterNoteBooks.sh
COPY jypyter_config.py /jypyter_config.py
COPY mycert.pem /mycert.pem

#use shell 
CMD bash jupyterNoteBooks.sh