FROM alpine:latest
MAINTAINER lei fireflykind@gmail.com

#mirr apk repositories
#RUN echo "http://mirrors.ustc.edu.cn/alpine/v3.2/main/" > /etc/apk/repositories

RUN echo "http://mirrors.ustc.edu.cn/alpine/v3.3/main/" > /etc/apk/repositories

RUN apk --update add bash
RUN apk add gcc
RUN apk add g++
RUN apk add python python-dev py-pip gfortran build-base

RUN mkdir ~/.pip/
RUN echo "[global]" > ~/.pip/pip.conf

#mirr pip 
RUN echo "index-url = https://pypi.mirrors.ustc.edu.cn/simple" >> ~/.pip/pip.conf

RUN pip install --upgrade pip

RUN pip install -v numpy==1.9.0
RUN pip install -v pandas==0.14.1

RUN pip install jupyter

RUN rm -rf /var/cache/apk/* /tmp/* /root/src/

EXPOSE 8888
VOLUME ["/data/notebooks"]

CMD ["jupyter","notebook","--no-browser","--port=8888","--ip=0.0.0.0","--notebook-dir=/data/notebooks"]
